# Generated by Django 3.2.7 on 2021-09-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.IntegerField()),
                ('x_point', models.FloatField()),
                ('y_point', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
